### ISSUE TITLE
Enable honeycomb agent configuration by IP and by node name simultaneously.

### ISSUE THREAD

**Issue by jinjagit** [honeycombio/honeycomb-kubernetes-agent#144]
On our kubernetes cluster, managed on Linode (LKE), we found we could either configure the honeycomb-agent (Deamonset)
1. by IP with k8s metrics enabled and no log watchers, using `fieldPath: status.hostIP` _or_
2. by (node) name with k8s metrics disabled and log watchers configured, using `fieldPath: spec.nodeName`.

Since we want both k8s metrics _and_ log watchers, this is less than ideal.

An obvious workaround is to configure 2 separate honeycomb agents. Ideally, this could be achieved using only one.

For context, our honeycomb-agent Daemonset mainifest (using `fieldPath: spec.nodeName`, line 102) is:

```
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: honeycomb-agent
  namespace: default
  labels:
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: honeycomb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: honeycomb
    app.kubernetes.io/version: 2.1.0
    helm.sh/chart: honeycomb-1.0.0
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: agent
      app.kubernetes.io/instance: honeycomb
      app.kubernetes.io/name: honeycomb
  template:
    metadata:
      labels:
        app.kubernetes.io/component: agent
        app.kubernetes.io/instance: honeycomb
        app.kubernetes.io/name: honeycomb
      annotations:
        <...snip...>
    spec:
      volumes:
        - name: config
          configMap:
            name: honeycomb-agent
            items:
              - key: config.yaml
                path: config.yaml
            defaultMode: 420
        - name: varlog
          hostPath:
            path: /var/log
            type: ''
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
            type: ''
      containers:
        - name: honeycomb-agent
          image: 'honeycombio/honeycomb-kubernetes-agent:2.1.0'
          env:
            - name: HONEYCOMB_APIKEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb
                  key: api-key
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /etc/honeycomb
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              readOnly: true
              mountPath: /var/lib/docker/containers
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: honeycomb
      serviceAccount: honeycomb
      securityContext: {}
      schedulerName: default-scheduler
      tolerations:
        - key: node.alpha.kubernetes.io/role
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 10

```

This issue is submitted at the request of Pierre (Honeycomb Solutions Architect), following his stalwart efforts to help us with this issue.
