### ISSUE TITLE
example watchers not working on google cloud kubernetes cluster

### ISSUE THREAD

**Issue by dvic** [honeycombio/honeycomb-kubernetes-agent#173]
The `quickstart.yaml` example uses these watchers:

```yaml
    watchers:
      - dataset: kubernetes-logs
        labelSelector: component=kube-controller-manager,tier=control-plane
        namespace: kube-system
        parser: glog
      - dataset: kubernetes-logs
        labelSelector: component=kube-scheduler,tier=control-plane
        namespace: kube-system
        parser: glog
```

When I played around with this I noticed that no logs were sent with a kubernetes cluster on Google Cloud. I guess this is because the `kube-controller-manager` and `kube-scheduler` components are managed and not visible? Is there a workaround for this? I'm also not sure if this is documented somewhere, should probably add it to the docs.
