### ISSUE TITLE
quickstart failed: secrets "honeycomb-writekey" not found: CreateContainerConfigError

### ISSUE THREAD

**Issue by stevemcghee** [honeycombio/honeycomb-kubernetes-agent#24]
secret is installed:
honeycomb-serviceaccount-token-nrslp   kubernetes.io/service-account-token   3         2m

agents won't start:
honeycomb-agent-v1.1-2j4s4     1/2       CreateContainerConfigError   0          3m
honeycomb-agent-v1.1-q45m6     1/2       CreateContainerConfigError   0          2m
honeycomb-agent-v1.1-thmll     0/2       OutOfcpu                     0          1s

running on GKE, with istio installed.

(apologies if this isn't the right forum, but the documentation suggests a quick start, which didn't happen)

**Comment by stevemcghee** [comment]
it appears that the namespaces were wrong.

the instructions from [here](https://docs.honeycomb.io/thinking-about-observability/getting-started-with/kubernetes/#getting-started) :
```
kubectl create secret generic -n kube-system honeycomb-writekey \
    --from-literal=key=YOUR_API_KEY
```

and

```
kubectl create -f https://honeycomb.io/download/kubernetes/metrics/honeycomb-heapster.yaml
```

result in the  honeycomb-agent-v1.1 daemonset running in the `default` namespace, but the secret was in the `kube-system` namespace

**Comment by stevemcghee** [comment]
i think i also need to open up an istio ServiceEntry for this to work, but i haven't figured it out yet.  something along the lines of:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: honeycomb
spec:
  hosts:
  - api.honeycomb.io
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: honeycomb
spec:
  hosts:
  - api.honeycomb.io
  tls:
  - match:
    - port: 443
      sni_hosts:
      - api.honeycomb.io
    route:
    - destination:
        host: api.honeycomb.io
        port:
          number: 443
      weight: 100
```

**Comment by toshok** [comment]
I know nothing about istio service config (maybe someone else can chime in here), but I have  corrected the docs to use a consistent namespace (changed the namespace to `default` in the `create secret` line.)  Thanks for the report on that!

**Comment by stevemcghee** [comment]
what's the best way to test connectivity from this pod?  like, does it need to access api.honeycomb.io over HTTPS or what?

im trying:
`kubectl exec -it honeycomb-agent-v1.1-p5k26  "/bin/sh`

then is there a basic healthcheck to run?  (eg: an unauthenticated `wget api.honeycomb.io/health` or something)

**Comment by tredman** [comment]
You can simply check `https://api.honeycomb.io/healthz` - this should return a 200.

I'm not yet familiar with Istio but will take a look. Does external HTTPS traffic from a pod need to be explicitly whitelisted by default?

**Comment by stevemcghee** [comment]
cool, this worked:
```
/go # apk update
/go # apk add curl
/go # curl https://api.honeycomb.io/healthz
{"message": "Oh, hello there."}/go # 
```

after also adding the istio routes:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: apk
spec:
  hosts:
  - dl-cdn.alpinelinux.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
```

and

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: honeycomb
spec:
  hosts:
  - api.honeycomb.io
  - www.honeycomb.io
  - honeycomb.io
  - api.ext.prod.honeycomb.io
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
    #  resolution: DNS
  location: MESH_EXTERNAL

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: honeycomb
spec:
  hosts:
  - api.honeycomb.io
  tls:
  - match:
    - port: 443
      sni_hosts:
      - api.honeycomb.io
    route:
    - destination:
        host: api.honeycomb.io
        port:
          number: 443
      weight: 100
```

the only problem now seems to be that istio isn't allowing the honeycomb agent to talk to the k8s master, which is resulting in the agent not being able to gather the data it needs to send off.

so, slightly closer :)
