### ISSUE TITLE
Log filtering for "nop" parser

### ISSUE THREAD

**Issue by to266** [honeycombio/honeycomb-kubernetes-agent#318]
**Is your feature request related to a problem? Please describe.**
I would like to collect only the logs where the application crashes (and thus is not able to send the usual otel info).

**Describe the solution you'd like**
Being able to NOT emit the logs if fields match some predictable pattern. In my particular case `starts-with` filtering that is normally available on refinery would be sufficient.

Note that in this case the logs are explicitly NOT structured - the panic / crash will not necessarily have a clear structure, so the `nop` parser must be used. This has the drawback that _any_ output at all matches, and everything ends up in the `log` field - polluting the dataset.

**Describe alternatives you've considered**
Doing the filtering on refinery, however it does not support filtering logs: https://github.com/honeycombio/refinery/issues/489
(which took a surprisingly long time to find btw, this could be documented better, front and center)

**Comment by kentquirk** [comment]
Hi, @to266. I think I understand that you'd like to process logs and drop entire events that match a given pattern. The current "drop" functionality operates at the field level.

This is effectively what a sampler does, except that we want to make a different kind of sampling decision.

As you note, refinery could do this if we implement that feature you call out, which is in fact a possibility in 2023.

But in the context of the agent, one way to handle this might be to add a new sampler type, let's call it a "regex" sampler, that would either drop or keep events containing fields that match a given regular expression pattern. 

In your case, configuration might look something like:

```
watchers:
- labelSelector: "app=crashy_app"
  parser: nop
  dataset: crash_reports
  processors:
  - sample:                   # Sample events: only send crashes
      type: regex
      onmatch: keep      # or drop
      field: log
      pattern: "^ERROR stack trace"
```

The tricky part is keeping this from turning into mini-refinery; we really don't want to go that far with this agent. 

I'd appreciate further feedback, as well as thoughts from others who might have other use cases.
