### ISSUE TITLE
documentation: add information on paths and exclude to the docs pages

### ISSUE THREAD

**Issue by kentquirk** [honeycombio/honeycomb-kubernetes-agent#323]
Our documentation does not include information on the `paths` and `exclude` fields in the `watchers` configuration section. Both of them are string arrays, and need to be specified as in the example below (both are optional fields and only need to be specified if automatic configuration is not working for you).

```yaml
watchers:
  - dataset: k8s-eventrouter
    labelSelector: app=eventrouter
    namespace: olly
    parser: json
    paths: 
      - "/var/log/pods/apps_*/*/*"
    exclude:
      - "/var/log/pods/apps_*/oldlogs/*"
    processors:
      - drop_field:
          field: old_event
```
