### ISSUE TITLE
Add a "rename_field" processor to rename a field

### ISSUE THREAD

**Issue by seh** [honeycombio/honeycomb-kubernetes-agent#36]
Given that processors are evaluated serially in order of definition, it's feasible to allow renaming fields collected earlier by the parser. If a field with the destination field name already exists, this processor should overwrite it. If no field with the source field name exists, it should proceed without effect. (Whether that's just one record missing the expected field or is due to a configuration mistake having misspelled the source field is hard to say.)

Imagine that we want to force all "msg" fields to be "message" instead:
```yaml
- dataset: "My Dataset"
  namespace: some-ns
  labelSelector: "app = kiam-server"
  parser: json
  processors:
  - timefield:
      field: time
      format: "2006-01-02T15:04:05Z07:00" # RFC 3339
  - drop_field:
      field: time
  - rename_field:
      source: msg
      destination: message
```
Here I proposed configuration field names "source" and "destination," but one can imagine many alternatives. Both are required to be nonempty, unless you want to tolerate an empty destination being equivalent to the "drop_field" processor. I think that would be a dangerous concession. If the two configuration field values are equal, either reject it immediately or treat it as a noop. I favor the former.
