### ISSUE TITLE
Enable additional static columns via config

### ISSUE THREAD

**Issue by tredman** [honeycombio/honeycomb-kubernetes-agent#42]
Sometimes it's useful to attach arbitrary fields to log events, such as cluster name or ID. We should support this by adding a section to the config to allow arbitrary key/value pairs to be appended to all events. Here's how it might look:

```yaml
watchers:
      - dataset: kubernetes-logs
        labelSelector: ""
        parser: glog
    verbosity: debug
# ....

additionalFields:
  - key: myField
    value: myValue
  - key: #...
```
