### ISSUE TITLE
Dynamic sampling appears to not work

### ISSUE THREAD

**Issue by niligulmohar** [honeycombio/honeycomb-kubernetes-agent#81]
This is tested with v2.0.0.

Configuring dynamic sampling, every retained sample has a sample rate that is exactly the goal sample rate. The expected behaviour is that less common types of events should be sampled at a lower rate.

We have a watcher with this configuration:
```
- dataset: APP
  labelSelector: "app.kubernetes.io/name=ingress-nginx"
  namespace: ingress-nginx
  parser: json
  processors:
    - keep_event:
        field: k8s.ingress
        values:
            - APP
    - sample:
        type: dynamic
        rate: 100
        keys:
          - status
```
Looking at the data set in usage mode shows that every kept event has a sample rate of exactly 100, despite receiving about 3 events per second with varying statuses. This would be expected for the first 30 seconds, before `dynsampler.AvgSampleWithMin.haveData` is set, but after that it should be sampling dynamically.

I would speculate that this is caused by the `dynsampler.AvgSampleWithMin` never (successfully) running its `updateMaps` function.
